language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: refaelkohen
  server: https://test.pypi.org/legacy/
  password:
    secure: sAWFCynatmqc/UXfcRaWVIK2AsZFoeVGD1hK1k0X3aWqUhCqhojRU2F+/J7U913Wr/A6O01rtLkqADK6H4prbDUKqsC82OtEeB44H+GqZEgGBpv+qo2eLMo1P1xn1XMmfxaDsLIFkvVOacRxOgRVDXj4kw7fmZ3vxrE1wu/SXu7/NJWESA3kCDZfaOBtypW9P9M3L205HZiqrupK5Xi5THcz1aN6+Qq8DfZGjdPKu504uzWrdZV5oB4NU1umQ3B7VONlgMSRo3k7myZuSSZLan36WYjQY2p8NX6hvcUC7uT3b9/oDE929bZqL1bNBFlmFqpMwdik1Gq5OPIV0Uf7IBYX4dYXSZRTgBX4K3K5ZW0IMn7FNT5+qiXaTU2ipnPwbgcf04OPafwG0jdXuE8zMpDhPPBuY1K2GnHxU6Ph4Ule0RwjeK59nUv2bxha8kzYuk/sM322YjN6vaVotFTN6mJ3JgRQxFNjlhhJDl19hcS2k35E6GWIpNC1f5YzmgfzqLU/G7EfaZMa2vWHE1XCc1BB3i09b8LzPFxW31XQZiDgGDO+oio2uoYn/UrSW2HCAFrPJsA5+j8mhGsqqkO9xNxPEAk5QzpEROb8gNS4T5DYpOrYN4m+9H2wT+bj2um2z0G1ilBx6gZi8n0Z4XMvxREqicAVImO+7JbDM068J48=
  distributions: sdist bdist_wheel
  true:
    branch: production
