language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: refaelkohen
  server: https://test.pypi.org/legacy/
  password:
    secure: it8IdkQgIqAe3K8uZp0OuTCXQYrDNxGZTcdkbXx+xxc/QruYFOS0Dass+2Oi2xscs18me7j6s03hDV472vB/Pm3ptZzOd2AMpyldQDCQ33rMksD1my/t3qZj25CanLhBfRuVPdAE/olv7SI4dyXSsJy77MV6RqKZCiRkQUMNaXPaoN31JHNY5AMEgRw4o+DN8x5LPWL4XlJDQNUecjsBnIX3dyGNLW1vTnosV8XG+U1I/LEy3BAreq6WN5LJmB/a5V+7GxfLtUCm+T7sSRsP+PBXR5q2h80akKKwiCTiv9h5jfnsTjvgB+fMD0TNXgAM0JA7XSRWvtLRs5lpKKC+vSuqfBaQwHOvMCliI5Dn7RVE4USHCYy1qzHlUEn2i21Gln+0B3WjRdWule03z4FncmWi8wTMarGVwIUHtCKGB6QDaSultJVh8F6pVXVLxHrsP6/ZahfV7iXERZvWRK3HuxIG+4rFg5ufbYXW6hyKTjGj/hdgQJ+fPt7qXXNPbc2Tt8rEJiOswRbiet1Ytb6M60EFU+r4P5jXfobCtXh1cIBBnSp8IWuBTKMxdVs/KaA6sivWmQ10QDzKmimHLNpHjV78jwCgYcA/J15a3DwlkqtiiFDwy4HrWIKinJrNhvxWoyWs5oC6J/74Ah/zf+9gwJz5MtMwHnCjPQHa4b716r8=
  distributions: sdist bdist_wheel
  true:
    branch: main
